### ISSUE TITLE
Manual install 

### ISSUE THREAD

**Issue by moonorblue** [cjwirth/RichEditorView#110]
Hi, I am new to swift. This is a really great library to use.
However, since I want to add some functionalities of my won, I want to install this without CocoaPods
I drag "RichEditorView" folder into the project, but my Xcode shows that "No such module ' RichEditorView', am I missing some steps to install the library ?
Thank you
![2017-03-08 12 00 27](https://cloud.githubusercontent.com/assets/1680971/23689651/0d711b6e-03f7-11e7-80dd-6983ce0f489d.png)
![2017-03-08 12 00 36](https://cloud.githubusercontent.com/assets/1680971/23689652/0da31f7e-03f7-11e7-8845-c0a4f5abd952.png)

**Comment by cjwirth** [comment]
Can you maybe upload a repo where this is happening? I never really considered manual installation when creating this.

**Comment by cjwirth** [comment]
I just tried adding it manually to a sample project and it worked.... 😕 

How are you integrating that into your project? It looks like you're just copying in the files, rather than actually bringing over the Xcode project file.

What you should probably do is:

1. Clone the library
1. Copy the directory into your project's directory.
1. Open your Xcode project
1. Drag the `RichEditorView.xcodeproj` file into your Xcode project structure.

And then it should probably work. 

You might need to go into the project settings for RichEditorView and turn on `Always Embed Swift Standard Libraries` and you might need to add the `RichEditorView` as a `Target Dependency` in you `Build Phases`, but I don't think these steps are necessary though.

**Comment by cjwirth** [comment]
I'm going to close the issue because I got manual integration working, and I don't think this is necessarily a problem with the repo itself.

I'm not shutting it down to ignore you, so feel free to comment back if you try it and it still doesn't work. 🚀
