### ISSUE TITLE
use richEditorView as the cell of uitabbleView

### ISSUE THREAD

**Issue by bruce107** [cjwirth/RichEditorView#152]
Is it possible to use richEditorView as the cell of uitabbleView?
There's a problem with sliding.  
Using OC programming

**Comment by cjwirth** [comment]
You definitely _can_, and I definitely _have_, but it's not necessarily recommended.

The problem comes down to embedding scroll views inside scroll views:

> You should not embed UIWebView or UITableView objects in UIScrollView objects. If you do so, unexpected behavior can result because touch events for the two objects can be mixed up and wrongly handled.
> https://developer.apple.com/documentation/uikit/uiwebview

I would suggest that you disable scrolling for the webview inside the RichEditorView. We had to do some workarounds when we did it, so we would have to grab the content size through the delegate method, and change the height of the cell if it changed. This was almost 3 years ago, so I'm sorry I don't remember the details!

Hope it works out for you :+1:
