### ISSUE TITLE
API addition proposal - currentSelection (for setting links safely)

### ISSUE THREAD

**Issue by mfrawley** [cjwirth/RichEditorView#21]
This seems an odd omission, surely to safely set a link I need to check beforehand if anything was selected? I can make a PR if we can agree on an API, I'd suggest something like: 

func selectionExists() -> Bool

**Comment by cjwirth** [comment]
I can definitely see the use to this!

In our app, we added an extra method to handle links -- wraps the current selection in an `<a>` tag if there is one, and just inserts if there isn't. It ended up being pretty long and probably more complex than it needed to be, so we didn't add it to the main repo. That's why something like this was left out :sweat_smile: 

Looks fine enough by looking at the diff, but I'll try it out and merge it in when I can confirm it works. Probably this weekend :+1:

**Comment by cjwirth** [comment]
Merged
