### ISSUE TITLE
Select line at cursor programmatically

### ISSUE THREAD

**Issue by c0cky** [cjwirth/RichEditorView#27]
Any ideas for how to auto select the current row of text where the cursor is at?

**Comment by cjwirth** [comment]
What do you mean by selecting the row that the cursor is at?

You mean having some method where it will take the current cursor position, and select all the text to the left and right of it, but not up and down at all?

I suppose it could be possible, but I'm not an expert at JavaScript. I'm not sure how you could get the beginning/end of the row...

**Comment by cjwirth** [comment]
ping

**Comment by c0cky** [comment]
Hmm.. sorry still haven't figured out a way to do it efficiently in javascript. I am trying to get the same functionality that Medium.com gives you. For example if you click bold, it highlights the entire line current line and turns it bold.

**Comment by cjwirth** [comment]
Ah I see what you mean now. This is actually more complicated than it seems like it would be.

I'm not sure if Medium is using a web view or not (my guess is probably not, there's no JS bundled in the IPA), but their use case is a little different, in that they change the formatting of the entire 'block' rather than just the words being typed.

I'd welcome a plugin that does something like this, but I don't think it belongs in with the main functionality. I feel like adding the code to find out where blocks start/end might be putting too much JS into the main project. 

This project was meant to be a starting point, with enough flexibility to let people make it work to their own specs. That being said, I do like the way Medium formats it, so if you find out a good clean way to do it, let me know and I'll make a plugin for it :+1:
