### ISSUE TITLE
can not deployment at ios7

### ISSUE THREAD

**Issue by KKKiller** [cjwirth/RichEditorView#32]
is there any solution to deployment at ios7

**Comment by cjwirth** [comment]
> Supports iOS 8 and 9 through Cocoapods or Carthage.

From the readme, no I don't support iOS 7.

I originally did, so you could probably get something running if you didn't use CocoaPods or Carthage, and included the project directly in your project and fix some errors or something. If I recall correctly, there is some API that I wanted to use that is only iOS 8+, so if you could find a workaround for that, you could probably get it working.

But iOS 9 has already been out for over half a year, and the iOS 7 market share is very small, so it's not something I'm going to put effort into changing. In fact, I've got a branch in the works that changes this to use WKWebView instead of UIWebView to be more modern.

**Comment by KKKiller** [comment]
thaks for your reply,i will have a try as your tips!

**Comment by cjwirth** [comment]
I just looked at the forks and stuff, and saw that https://github.com/jjimeno/RichEditorView has something called "backport to iOS 7" or something. Might be useful to look at, even though it's a relatively older version.
