### ISSUE TITLE
i want to use the richTextView to replace the funtion of UITextView to show HTML string

### ISSUE THREAD

**Issue by KKKiller** [cjwirth/RichEditorView#38]
i want to use the richTextView to replace the funtion of UITextView to show HTML string . After i set HTML string to richTextView,how could i get the textView height? if the HTML string contain remote image, will the height be calculate correct? i
~~~ swift
public private(set) var editorHeight: Int = 0 {
        didSet {
            delegate?.richEditor?(self, heightDidChange: editorHeight)
        }
    }
~~~
will this method working ?

**Comment by cjwirth** [comment]
It depends on the timing. If you ask the editor for its `editorHeight` immediately after loading the string, it probably won't be loaded yet, and will return 0. That's what the delegate method is for. 

Bad:

~~~ swift
editor.setHTML(htmlString)
let height = editor.editorHeight
~~~

Good:
~~~ swift
override func viewDidLoad() {
...
}
~~~

**Comment by KKKiller** [comment]
OK  ,it is work well. so i want to know that if i use the richTextView in a tableview , and every cell will contain a richTextView, will it still be smooth ?

**Comment by cjwirth** [comment]
You can get it to work, but it's not the ideal situation. There are certain things you will have to do to get it to work. We did it, and while it works, it's not perfect. In particular the problems we faced were:

- No cell reuse. Re-loading the HTML each time the cell is displayed takes too long and is not smooth
- Wait for all cells to finish loading before displaying. This could be dangerous if you are loading some non-local content, and for some reason it just never "finishes" loading. 
- Reloading each if inner heights change. Not too bad, but something to be aware of.
- Apple recommends against putting UIScrollViews inside UITableViews. So turn off the scrolling of the UIWebView's UIScrollView

If you have a lot of cells inside, and there is a lot of content, it might end up taking up a lot of memory -- especially because you can't reuse cells, or else your display won't be smooth. Waiting for all the cells to load first can take a long time, and can lead to some confusing logic. 

That being said, I did some manual testing with a _ton_ of cells and images, and it worked _okay_. I even had multiple view controllers with the same content being displayed multiple times.

It's not an approach I recommend, but yes, it's something that I have done.

**Comment by KKKiller** [comment]
so if i want to show HTML string contain remote image in the tableViewCell,is there any better method you will sugesst?

**Comment by cjwirth** [comment]
We ended up not showing any images in the rich editor view. The way our system worked was to have images in different "blocks" than rich text. Still, all of the problems I wrote about will happen whether you have images or not.

I don't know if there is a better way to do it, or if you just have to grit your teeth and do it.
