### ISSUE TITLE
Im eagerly hope you can merge the branch to master which have fixed the bug of scroll-with-cursor

### ISSUE THREAD

**Issue by KKKiller** [cjwirth/RichEditorView#44]
the richEdittor is really usaful to my project. if the cursor could be fixed,it is really exited. and i am appreciate of your effort.and hope you could fix this bug.last time you said the branch  will be merged before this weekend ,and i am watting for you .thank you very much.

**Comment by jesiegel1** [comment]
working on the final fix today hopefully

**Comment by cjwirth** [comment]
Thanks @jesiegel1 , looking forward to it! I am also looking forward to merging this branch in!

@KKKiller if you want to use the not-quite-done-yet branch, you could tell CocoaPods to use the in-progress branch if you wanted, by specifying the git repo:

~~~
pod 'RichEditorView', :git => 'git@github.com/jsiegel1/RichEditorView.git'
~~~

I'm not sure if that's 100% correct, but the idea is to point it to the git repo rather than using the official released version.

Closing this issue because there's already an open (hopefully soon-to-be-closed!) pull request.
