### ISSUE TITLE
When i  run the sample,it got errors from the keyboardManager ,i am not good at swift ,how should i tackle with it ?

### ISSUE THREAD

**Issue by KKKiller** [cjwirth/RichEditorView#45]
NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(KeyboardManager.keyboardWillShowOrHide(_:)), name: UIKeyboardWillShowNotification, object: nil)

error:  missing argument for parameter 'selector' in call

**Comment by jesiegel1** [comment]
what version of Xcode are you using?

**Comment by KKKiller** [comment]
7.2.1

**Comment by jesiegel1** [comment]
The selector syntax is different for Swift 2.2.  For your version, you should use `NSNotificationCenter.defaultCenter().addObserver(self, selector: Selector("KeyboardManager.keyboardWillShowOrHide:"), name: UIKeyboardWillShowNotification, object: nil)`

**Comment by cjwirth** [comment]
The syntax for selectors was improved in Swift 2.2, and Xcode 7.3. Since Xcode 7.3 official was released, I upgraded the sample project to be run on 7.3 instead of 7.2.

If you still want to run it on 7.2, you can change it from `#selector(KeyboardManager.keyboardWillShowOrHide(_:))` to `Selector("keyboardWillShorOrHide:")` and it should work. (I didn't try it, so the syntax might be wrong, but you need to use string-based selectors rather than the new ones)

**Comment by KKKiller** [comment]
it  success when i run on 7.3,but   it was not scroll when the word is under the keyboard,

**Comment by jesiegel1** [comment]
because the fix for that bug hasn't been merged yet, it's a wip. please see [https://github.com/cjwirth/RichEditorView/pull/34](url).

**Comment by cjwirth** [comment]
> it success when i run on 7.3

Awesome, closing this issue then 👍 

> but it was not scroll when the word is under the keyboard

I made a comment in pull request #34 so you can use the in-progress version of the project that should be fixed. It'd be great if you could use it and make sure it works before we merge it in!
