### ISSUE TITLE
placeholder incorrect 

### ISSUE THREAD

**Issue by codwam** [cjwirth/RichEditorView#48]
While input 123 and clean, placeholder is hide
And the only insert one image as well.

**Comment by cjwirth** [comment]
Hey! Sorry you had a problem, thanks for letting me know 👍 

I'm not sure what's going on? You input "123", and then clear the text, but the placeholder doesn't show up? 

And what about inserting the image? Does the placeholder still appear after inserting an image into an empty editor?

Could you take screenshots, or upload a gif of the problem happening so I can understand it better?

**Comment by codwam** [comment]
You can use your demo to test..
1.enter '123' and clear, not appear
2.click image button on toolbar , placeholder still appear

And I use below can fix it, but not good:
`    func richEditor(editor: RichEditorView, contentDidChange content: String) {
        if content.isEmpty || content == "<br>" {
            self.setPlaceholderText("正文")
        } else {
            self.setPlaceholderText("")
        }
    }`

**Comment by cjwirth** [comment]
Are you working off of the master branch, or one of the releases?

> 1.enter '123' and clear, not appear

This is actually working for me on master.
I added 

```swift
editorView.setPlaceholderText("Enter Text")
```
to `viewDidLoad` in the ViewController, and it's still showing up when I type in "123" and then "Clear" the text.

> 2.click image button on toolbar , placeholder still appear

Ok yeah this one is weird, and I should fix it.

**Comment by cjwirth** [comment]
OK, so the problem is that right now it's just checking whether there is any text input or not. This is kind of weird, because it also means that lists without any text in them yet will still show the placeholder.

I think what we could do is first check if there is text. If there is text == no placeholder. If there is no text, well then we have to check if there is any other element in the editor that counts as "content." I don't really want to go through the tree of elements and see if it finds a certain "content" node by checking if each node == "img" or node == "ul" or whatever. There's probably a better way than that, but I don't do much front end JS, so I don't really know?
