### ISSUE TITLE
Where is the cursor?

### ISSUE THREAD

**Issue by Ying1986** [cjwirth/RichEditorView#50]
@cjwirth 
Hello

When I input text, view doesn't scroll to the cursor position.

https://www.dropbox.com/s/qsn324g41ns0o2e/Cursor.mov?dl=0

PS: After `pod install` code is different with your example code.
For example, in you sample code has `adjustContentOffsetFromCaretPosition`, but **master** branch has no it.

**Comment by cjwirth** [comment]
The master branch has the bugfix for this merged in, but I haven't released it. There might be some bugs (there are 2 issues about the placeholder right now) that might be due to this bug fix.

This issue, however, has already been fixed on master.
You can use 
``` ruby
pod 'RichEditorView', :git => 'git@github.com/cjwirth/RichEditorView.git', :branch => 'master'
```
to install the master branch into your project instead of the current release.
