### ISSUE TITLE
How can I change font.

### ISSUE THREAD

**Issue by Ying1986** [cjwirth/RichEditorView#52]
In iOS9, default system font is `SF` family fonts.

How can I update font?

**Comment by cjwirth** [comment]
That's a good point. Maybe I should change that in the default CSS.
If you want to do it manually, you'll have to change the [style.css](https://github.com/cjwirth/RichEditorView/blob/master/RichEditorView/Assets/editor/style.css#L59) file where it defines the font.

Otherwise, you can load your own custom CSS file to change the styling if you want. I wrote about how to do so in [this issue](https://github.com/cjwirth/RichEditorView/issues/43) before, so it will probably work for you.
