### ISSUE TITLE
How can I highlight buttons when it's style on

### ISSUE THREAD

**Issue by Ying1986** [cjwirth/RichEditorView#53]
https://cloudup.com/c-dgqttfpZY

If current selection is bold, `bold` button is highlight.

**Comment by cjwirth** [comment]
This is something we did in our app as well, but it's kind of a lot of code. I didn't want to include it in the library because it's not really something necessary for everyone, and there are tons of opportunity for bugs.

Basically, what we are doing is -> 

1. Set an event listener for "selectionchange"
1. In the listener, get a list of all the currently selected styles (by using `document.queryCommandState`, and some other stuff)
1. Send that list to the RichEditorView through a custom action .I should write something about how to do this... Basically, in the JS, you set up a string like `name-of-action?query=parameters&more=params` and send that into `RE.customAction(actionString)` . 
1. That string from 👆 will get sent to the `func richEditor(editor: RichEditorView, handleCustomAction action: String)` delegate method. 
1. Parse the string to get out the parameters of what styles have been applied
1. Reset the UI based on what styles are currently selected

If there is enough demand, I'll think about adding it to the library, but there's a lot of stuff that I don't think is needed for every use case. I mean, you're going JS -> Swift every time the selection changes, so it's not as "lightweight" as it could be, if you're not even using it.

**Comment by Ying1986** [comment]
@cjwirth 

How can I add `selectionchanged`?

**Comment by cjwirth** [comment]
There is no delegate for that, it's taken care of in the JS. This library is really just a _very_ thin wrapper around a UIWebView using the JS `contentEditable` API, so most of the customizations you will want to make need to be made with JS or CSS.

You will need to have a file with your custom JS. You'll have to load it into the view, like in the posts I've shown before. 

You can do pretty much anything you want in your custom JS file. I'm certainly not an expert at JS, so I can't really tell you how to do too many things. I recommend reading about it at [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript) .

But to answer you question, to add an event listener for "selectionchange", you need to add this to your custom JS file:

```javascript
document.addEventListener("selectionchange", function() { 
    // Do stuff that will called every time the selection changes
});
```

You will also do well debugging the webview inside the simulator with Safari. [Here's an old article that explains how](http://webdesign.tutsplus.com/articles/quick-tip-using-web-inspector-to-debug-mobile-safari--webdesign-8787) <-- it's old, but was the first result on Google

**Comment by cjwirth** [comment]
We can continue the discussion in this issue, because it actually has the history of the conversation.

> I have tried to set BreakPoint on func richEditor(editor: RichEditorView, handleCustomAction action: String), but app doesn't stop at that time when I changed selection.

The delegate method isn't meant to be called when the selection changes. It's called when you send a custom action to the editor from JS.

So, for example, to get the delegate method calling, you'll have to do something like this:

```javascript
document.addEventListener("selectionchange", function() { 
    RE.customAction("my-action");
});
```

And then, assuming you have your delegates set up and everything, `func richEditor(editor: RichEditorView, handleCustomAction action: String)` should be called with `my-action` as the action passed in.

**Comment by Ying1986** [comment]
@cjwirth 

Thank you.

**Comment by Ying1986** [comment]
@cjwirth 

How can I get current typing states (bold, italic, ...).
I'm trying to update toolbar buttons on selectionChanged callback delegate.

But when I press **bold**, `document.queryCommandState` returns no.
only when I input one character, it returns `true`.

**Comment by cjwirth** [comment]
> How can I get current typing states (bold, italic, ...)?

I've outlined the steps you need to take up above. Calling `document.queryCommandState('bold');` etc. should give you the current state of the style.

I'm not an expert on the `contentEditable` API, so if something is behaving weirdly, I probably won't know why.

> I'm trying to update toolbar buttons on selectionChanged callback delegate.

Sure, I've outlined the steps of how to do this up above. Make a selectionchanged listener, get the current state, send it back to Swift through a `customAction`, use that data to update your UI.

Actually, you will probably need to make a custom toolbar, if you haven't already, because the current toolbar doesn't have support for things like that.

> But when I press bold, document.queryCommandState returns no.
only when I input one character, it returns true.

Sorry, I don't really know why this is. Could be that it returns `false` if the content is empty? I don't know, there's probably documentation for it somewhere online. https://w3c.github.io/editing/execCommand.html might have something

**Comment by Ying1986** [comment]
@cjwirth 

I have found toolbar item doesn't post actions.
For example, I can't catch event when user click **bold** on empty text.

Sso should I add custom action?

**Comment by cjwirth** [comment]
Aaah, I forgot about that. 
Yeah, you will probably need a custom action for that. It shouldn't be too hard, though. Just call the bold action on the editor, and then run the JS that updates the currently selected styles.

For example, in my app I have something kind of like this: (it's actually very different, but the idea is the same):
```swift
let item = RichEditorOptionItem(image: nil, title: "Bold") { toolbar in
    toolbar?.editor?.bold()

    // This should probably be the same thing you do in your `selectionchange` listener
    toolbar?.editor?.runJS("updateSelectedStyles();")
}

toolbar.options.append(item)
```

**Comment by ithakkarritesh** [comment]
I followed those step as you mentioned but could not able to achieve that functionality like highlight buttons when it's style on. so please give me brief description. thank you.

**Comment by Leelasai99** [comment]
can you help me on this or provide me example?
