### ISSUE TITLE
I can't format such as font size, color, line-height,...

### ISSUE THREAD

**Issue by Ying1986** [cjwirth/RichEditorView#54]
https://github.com/cjwirth/RichEditorView/issues/43
I have checked and tried it, but I can't see changed font color.

following is the js value on runJS.

https://cloudup.com/cdGI1osZqqj

And where is `cleanStringForJS`?

**Comment by cjwirth** [comment]
Your changes probably aren't being applied because the JS has unescaped characters in it, like newlines. That will be an error when it is evaluated by the UIWebView.  You should run your CSS through this clean function before passing it into the JS string:

``` swift
func cleanStringForJS(string: String) -> String {
    let substitutions = [
        "\"": "\\\"",
        "'": "\\'",
        "\n": "\\\n",
    ]
    
    var output = string
    for (key, value) in substitutions {
        output = (output as NSString).stringByReplacingOccurrencesOfString(key, withString: value)
    }
    
    return output
}
```

I'm not sure if its the best way to do it, or if its even complete. But it worked for the JS we were using to customize our app.
