### ISSUE TITLE
Where is the delegate for selectionchaged ?

### ISSUE THREAD

**Issue by Ying1986** [cjwirth/RichEditorView#58]
I can't find the delegate for **selectionchaged**?

**Comment by cjwirth** [comment]
I explained how to set up a listener for it in [this comment](https://github.com/cjwirth/RichEditorView/issues/53#issuecomment-221754270) . 

There is no delegate method for it, because it takes place inside JS. To send some data to Swift from JS, you have to send a string into `RE.customAction(string)` which will be sent into the RichEditorView's delegate's `func richEditor(editor: RichEditorView, handleCustomAction action: String)` method.

**Comment by Ying1986** [comment]
@cjwirth 

Don't this close comment. This is not resolved.

I have tried to setBreakPoint on `func richEditor(editor: RichEditorView, handleCustomAction action: String)`, but app doesn't stop at that time when I changed selection.

**Comment by cjwirth** [comment]
> Don't this close comment. This is not resolved.

The conversation started in [this issue](https://github.com/cjwirth/RichEditorView/issues/53#issuecomment-221754270), so we can continue it in there too. I've reopened it.
