### ISSUE TITLE
hello.

### ISSUE THREAD

**Issue by xingze0308** [cjwirth/RichEditorView#61]
Hi.
If I want to use in OC.  
What should I do ？
Can you give some hints？
Thank you very much.
Good luck to you!

**Comment by cjwirth** [comment]
You should be able to use the default one just fine. Look at the sample project, there is a view controller written in Objective-C that is using it.

If you want to make some custom options for the toolbar, you will have to make your own options that conform to the `RichEditorOption`  protocol, because the default ones are `enum`s and `struct`s, which can't be used from Objective-C.

**Comment by xingze0308** [comment]
Thank you very much you can back to my message。

I study again!

😃😃
