### ISSUE TITLE
How to get selected text when user click insert link button?

### ISSUE THREAD

**Issue by whitewizard007** [cjwirth/RichEditorView#64]
I run your example, i found this one:

    func richEditorToolbarInsertLink(toolbar: RichEditorToolbar) {
        // Can only add links to selected text, so make sure there is a range selection first
        if let hasSelection = toolbar.editor?.rangeSelectionExists() where hasSelection {
            toolbar.editor?.insertLink("http://github.com/cjwirth/RichEditorView", title: "Github Link")
        }
    }

I would like to get highlight text then i can replace your github url with the highlight text that user selected.

**Comment by cjwirth** [comment]
You mean you want to add a URL to the text that the user already has highlighted? 
That's what it's already set up to do... so maybe I'm misunderstanding the question?

**Comment by whitewizard007** [comment]
Let say that i type "www.google.co.th" in RichEditorView, highlighted it, then click "Link button" on toolbar.
So.. richEditorToolbarInsertLink is running.

My question is.. how i can get "www.google.co.th" inside the method ?
If i can get it, i will replace "http://github.com/cjwirth/RichEditorView" with a variable that keep "www.google.co.th"

**Comment by cjwirth** [comment]
Oh I see what you mean!

Unfortunately there's no _good_ way to get that text right now. Your best bet is probably just calling something like 
```swift
editor.runJS("document.getSelection().getRangeAt(0).toString()")
```
or something similar, in order to get the text that is currently highlighted. The problem is that it won't give you newlines, or images, or lists, or any other formatting.

If that's good enough for you, then great! Otherwise you'll have to write some other JS to run in the editor.

**Comment by whitewizard007** [comment]
Yeah. It's work. Thank you so much for your best support (:
