### ISSUE TITLE
Using RichEditorView, apple can reject my app?

### ISSUE THREAD

**Issue by chgarcia79** [cjwirth/RichEditorView#67]
I read in an issue that apple rejected apps for using RichEditorView,it's true? there are any way to  fix this? i need edit html on my app.

Thks.

**Comment by cjwirth** [comment]
Yes, we are using a bad, dirty private API to hide the UIWebView's input accessory view. I already have a ticket open about it here: https://github.com/cjwirth/RichEditorView/issues/35

You can read more about it at another project https://github.com/driftyco/ionic-plugin-keyboard/issues/179 that was having the same problems. I haven't gone and made the same changes as them, because I thought maybe I could do something better. Maybe I should go and fix it, just in case.

Closing this issue, because it's basically a duplicate. If you want to continue discussion, though, that's fine too 😄

**Comment by cjwirth** [comment]
That being said, there are a (large) number of apps using the same API in the AppStore, so there's also a chance you won't get rejected as well!

**Comment by MHX792** [comment]
Any news on this?
