### ISSUE TITLE
WKWebView instead of UIWebView

### ISSUE THREAD

**Issue by y25zhao** [cjwirth/RichEditorView#68]
Apparently, UIWebView has lots of memory issues and it's slow. Can we consider switch to use WKWebView which is what Apple suggested to use from WWDC?

**Comment by cjwirth** [comment]
Hey! Thanks for your interest in the project 😃 

Hope you don't mind, but I'm doing to close this issue as a [duplicate](https://github.com/cjwirth/RichEditorView/issues/24) .

Yes, it's something I'm considering, but it would mean rearranging a lot of the logic, because you can't run JS synchronously in WKWebView. It might not be a big problem, but it would basically mean rewriting a lot of the library.
