### ISSUE TITLE
Objective-C Support

### ISSUE THREAD

**Issue by ShadeApps** [cjwirth/RichEditorView#7]
The component is great and awesome and it's a breeze to use in Swift.

However, I faced with a problem while adding it to existing objective-с class - I can't make Xcode see the corresponding class.

If I just use the `@class` directive, the complier says it's a forward class declaration. 

I suspect that we just can't use this great library in Objective-C which is a huge downside. Am I wrong?

**Comment by cjwirth** [comment]
You can use it from Objective-C, but there are some problems with it right now (I'll fix some of them).

You just have to import 
```
#import <RichEditorView/RichEditorView-Swift.h>
```
to be able to use it from Objective-C.

Here are some problems, however:
- Some protocols are not visible from Objective C. This can be fixed by adding `@objc` to the beginning of the declaration of the protocols. I'll fix this one
  - [ ] RichEditorDelegate
  - [ ] RichEditorToolbarDelegate
  - [ ] RichEditorOption
- Default Options are Swift-only. RichEditorOptionItem is a struct, and RichEditorOptions is an enum. These could be somewhat re-implemented in ObjC, or re-worked. 

There might be more problems, but those are the most obvious. There is nothing in the way it was build that makes it inherently unusable from Objective-C though.

**Comment by cjwirth** [comment]
Well, it turns out the _RichEditorOption_ isn't going to want to support Objective-C very nicely. 

The struct _RichEditorOptionItem_ and enum _RichEditorOptions_ both conform to it. Making it an `@objc` protocol will throw an error that only classes can conform to _RichEditorOption_. 

I could just rework everything to be classes to be Objective-C friendly, but that would change a lot of things, and end up being a pretty big breaking change.

Do you want to use the _RichEditorToolbar_ or could you use something custom? I have a [branch where you can set the keyboard accessory](https://github.com/cjwirth/RichEditorView/issues/6) if that's what you need. If so, I think I could make everything except the _RichEditorOption_ support Objective-C, without having to break the way things are working so far.

**Comment by ShadeApps** [comment]
Well, if for now the only problem lies in the RichEditorToolbar, I think we'd better be without it than without the whole component. 

I don't have that much expertise in Swift to help you rewrite it to be 100% Obj-C usable but I would be glad to help

**Comment by cjwirth** [comment]
Yeah I think you're right. 

It would also be possible to add a some kind of wrapper class around it, so it can be used from Objective-C. 

I updated the `development` branch with some better Objective-C support. The sample project also includes a view controller using the _RichEditorView_. It's basically the same as the Swift version, but without the full toolbar support.

**Comment by cjwirth** [comment]
Check out [2.0.0](https://github.com/cjwirth/RichEditorView/releases/tag/2.0.0). The Obj-C stuff I added is in there now.

**Comment by faizantariq1** [comment]
Sample code for RichEditorView is attached below. for objective c.

[ZSText.zip](https://github.com/cjwirth/RichEditorView/files/3928380/ZSText.zip)
