### ISSUE TITLE
Gesture and Swipe support

### ISSUE THREAD

**Issue by hadynz** [cjwirth/RichEditorView#71]
I am considering porting this rich text editor into a react native component for a project that I am working on. One of my requirements though is to be able to support gestures; swiping left or right on a sentence applies text styling such as bolding and indentation.

Being very foreign to the iOS development world wondered if you had an idea how your the rich text editor can be configured to listen to gestures on individual blocks of text.

Would appreciate any thoughts on the matter.

**Comment by cjwirth** [comment]
Cool! I've never done react native, so that seems pretty neat! 😃 

> Being very foreign to the iOS development world

Are you from the world of front-end JavaScript? Because if so, you might be able to figure this out better than I can, to be honest! This library is basically just a thin wrapper around a `UIWebView` that has a `contentEditable` `div` inside it, than I then funnel some JavaScript functionality to.

I have some `UIGestureRecognizers`, which may or may not affect what touches make it to the JS context itself -- I haven't tried doing any kind of swiping functionality... If so, you might be able to register a new `UIGestureRecognizer` on the web view, and just pass the relevant information to it, and then do some processing down in that level? I'm not sure, I'm just spouting out ideas...

**Comment by hadynz** [comment]
Interesting... didn't realise that this library was built on top of a JS implementation and not native as I thought initially.

What's the performance like?

**Comment by cjwirth** [comment]
> Interesting... didn't realise that this library was built on top of a JS implementation and not native as I thought initially.

Yeah, it's only a very thin wrapper, opening some of the `contentEditable` APIs to be available from native code. Plus a little bit extra to make sure it's functioning.

> What's the performance like?

The guy who's writing his entire app in JS (react native) is asking about performance of a component using JS, haha 😜 

I know a few apps that are using it production. One of them has multiple (potentially a _lot_) onscreen at the same time. I'd suggest trying it out and making a sample of your use case to see if it works for you.

One issue that might come up is that, since it's a web view, loading is asynchronous and might take a while depending on the content. This can make layout take a while, which can be an issue if you have many of them in a table view or something.

**Comment by cjwirth** [comment]
Closing this issue, because making a reactive native component is not on my radar. Someone else is welcome to though.
