### ISSUE TITLE
How to focus editor right as the view appears

### ISSUE THREAD

**Issue by markbao** [cjwirth/RichEditorView#75]
Hi there, I'm trying to focus the editor right when the view appears (after being called by `presentViewController`). Unfortunately, calling `editor.focus()` in `init()` doesn't work, and calling `editor.focus()` on `viewDidAppear()` takes too long (about a second passes before the keyboard is shown). Is there another way to do this, such as by injecting JS or by adding an autofocus field to the editor?

**Comment by markbao** [comment]
I was able to solve this by adding this JS directly to the `rich_editor.html` in the pod, but hoping there is a cleaner solution that avoids directly editing the module.

```
<script type="text/javascript">
    window.onload = function() {
        document.getElementById("editor").focus();
    };
</script>
```

**Comment by cjwirth** [comment]
I hadn't thought of this when I was using it -- just calling `editor.focus()` in `viewDidAppear()` was good enough for the situation I was in. I didn't notice it taking a whole second...

Since you have to wait for the web view to load before you can do anything, including injecting JS... I'm not really sure if there is anything else you can do... Definitely something to keep in mind and try to come up with a solution to...

**Comment by cjwirth** [comment]
Closing this issue, because I'm not sure if there is any better way to do this, without making some big structural changes.

**Comment by chaoticbit** [comment]
For swift 3 iOS 10.2 I was able to solve this by manually triggering the focus using `runJS()` method without any delay or lag. It works smoothly.

```swift
override func viewDidAppear(_ animated: Bool) {
    editorView.runJS("document.getElementById(\"editor\").focus()")
}
```

**Comment by AlessandroMendozza** [comment]
Solved with `DispatchQueue`
```swift
override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            self.editorView.focus()
        }
}
```
