### ISSUE TITLE
scrolling issue if keyboard shown

### ISSUE THREAD

**Issue by Hendrik44** [cjwirth/RichEditorView#79]
Hi,

I've found an scroll issue if the EditorView height is greater than the space when the keyboard will shown. Then yo get a strange scrolling issue that overlays other views.

Ive made a fork and edit the RichEditorViewSample project so you can pull and reproduce the issue:
https://github.com/Hendrik44/RichEditorView

**Comment by cjwirth** [comment]
Hey, thanks for taking a look at the project 😃 

I see 2 things that could be considered problems when running your sample project, and I'm not sure which one you're talking about:

When you input text that goes further than the space allowed, so that it has to scroll: 
1. The upper part of the view escapes the bounds of the view
2. The scrolling is off, and appears below the keyboard

For 1, all you have to do is set the RichEditorView, or its superview to clip its subviews, and it should be fine. 

Number 2 actually isn't a bug, because it works the same way as UITextView -- when you input more text, it scrolls so that the text is visible on the bottom of the view, not necessarily above the keyboard.

Let me know if that answers your question 👍

**Comment by Hendrik44** [comment]
Thanks for your fast reply. Solution one worked for me 👍

But if the keyboard was shown and the editor has no content, why i can scroll? Doesn't the editorview update the contentsize if the keyboard will shown?

**Comment by cjwirth** [comment]
Oh I see, that's interesting. I actually don't know why it's doing that, and it fixes itself if you input some text. I don't do anything when the keyboard is shown, so it might be something going on underneath in the actual UIWebView.

**Comment by Hendrik44** [comment]
[Test.zip](https://github.com/cjwirth/RichEditorView/files/437541/Test.zip)
In your sample Project i can't also reproduce the the scroll behavior and it just fixed when you input some text. So I've  made a Xcode Testproject, so you can check the scroll behavior.

**Comment by cjwirth** [comment]
I'm not sure if this bug still exists, but scrolling has been an issue for a long time, so I made a megathread about it. Sorry, but I'm going to close this issue and consolidate scrolling problems into that one.
