### ISSUE TITLE
Focus and insertHtml in UITableViewCell

### ISSUE THREAD

**Issue by yasinbor** [cjwirth/RichEditorView#81]
I couldn't find any way to insert html in RichEditorView while it is in UITableViewCell.

From main view user selects any cell for detail view and i push selected cell's html content from main view to detail view.
In detail view i have also tableView, in one of cells there is RichEditorView and i feed it with html string that i passed. 

`cell.richTextEditorView.insertHtml(stringFromPreviousPage)`

But this doesn't work. RichTextEditor not getting called.
I tried to make it first responder but it returns false to `richTextEditorView.canBecomeFirstResponder()`

I tried to make cell first responder and succeed and after that tried to make richTextEditor firstResponder but it didn't worked either.

If i tap on richTextEditor and insertHtml, it works.

But i need to insertHtml without any user action while view is loading. 
How do i accomplish it?

**Comment by cjwirth** [comment]
Hey! Sorry you're having troubles with the project...

I think I need more information about how you're setting up the table view and the editor view. Where is this `insertHtml` method coming from? Are you calling it before the editor view has finished loading? Could the data be getting overwritten because it's in a table view cell? 

I don't think I know enough about your setup to know what's actually causing the problem.

**Comment by yasinbor** [comment]
Hey thank you for replying, 

Sorry i forgot that insertHTML extension that i wrote to RichTextEditor.

I want to put html in to richTextView. I am calling it after i check if richTextView is nil or not. Content can't be overwritten because i also check if it still exists.

As i said before when user taps cell i want to push html content into richtextview one of cells in the next pages tableview. And user will be able to edit it.

How do i load ready html content into richtextView?

**Comment by cjwirth** [comment]
I have an idea of what you're doing, but I'm not looking at your code, so I don't know 100% if this will work or not, but I think it might.

Instead of inserting the HTML and focusing the editor immediately (like in viewDidLoad or something), try doing it in one of the delegate methods like `richEditorDidLoad` or `contentDidChange`. 

`richEditorDidLoad`  is called when the editor has finished its internal loading, and should be ready for interaction. 

`contentDidChange` is called whenever the content inside the editor changes, so you might not want to put anything that takes a long time in there. Like in the sample, we are setting text in the preview view whenever the content changes.

Let me know how it goes for you 👍

**Comment by yasinbor** [comment]
Than you for reply, i was able to accomplish it exactly the same way you think. My problem was pushing content into richEditor before it is internally loaded. After it finished loading, i set html content and it works like charm. 
Thank you for your time, feel free the close anytime.

**Comment by cjwirth** [comment]
Cool! Yeah, sorry for the late reply, but I'm glad you got something working 😃
